# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: prod
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Print the env var
        run: echo $EENNVV

      - uses: microsoft/variable-substitution@v1 
        with:
          files: 'hello.yml'
        env:
          Var1: "value1"
          Var2: "value2"

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          cat hello.yml
          git clone https://github.com/ramuyk007/gitopsone.git

      # - name: Checkout seconf repository
      #   uses: actions/checkout@v3
      #   with:
      #       repository: ramuyk007/gitopsone

      - name: copy file hello.yml
        run: |
          ls
          ls gitopsone/dev
          mv hello.yml gitopsone/dev/hello.yml

      - name: commit and push
        run: |
          cd gitopsone
          git config user.email "ykramu007@gmail.com"
          git config user.name "ramuyk007"
          git add "dev/hello.yml"
          git commit -m "add"
          git remote set-url origin git@github.com:ramuyk007/gitopsone.git
          git push
